image: node:16.19.0
cache:
  paths:
  - node_modules/
before_script:
- npm install pnpm -g
- pnpm install
- pnpm run version
pages:
  script:
  - pnpm run docs:build
  - rm -rf public
  - mkdir public && cp -rf src/.vuepress/dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
